### ISSUE TITLE
any command doesn't work

### ISSUE THREAD

**Issue by jucogjucogi** [FabricMC/fabricmc.net#10]
any command doesn't work
chat says this in red color:
cannot invoke com.mojang.brigadier.commanddispatcher.execute (String, Object) because net,fabricmc.fabric.impl.command.client.ClientCommandInternals.activeDispather is null
re-launching game or re-entering the world does not work too.

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
