### ISSUE TITLE
The game crashed whilst initializing game Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'prominent'!

### ISSUE THREAD

**Issue by blassefemme** [FabricMC/fabricmc.net#105]
I clicked on the 'update all' thing in the content tab of the prominence II modpack. I haven't been able to launch the modpack since. I don't know how to read crash reports and i need help figuring out how to fix this. 
[crash-2024-08-12_22.25.42-client.txt](https://github.com/user-attachments/files/16591542/crash-2024-08-12_22.25.42-client.txt)

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
