### ISSUE TITLE
Broken validation for mod package name

### ISSUE THREAD

**Issue by UpcraftLP** [FabricMC/fabricmc.net#107]
It appears that the validator for mod package names does not accept single letter packages.

`com.example.a` is a perfectly valid package, but the validator disagrees, and thus does not let me generate a template ZIP.

![image](https://github.com/user-attachments/assets/ed93f1c4-1c80-492c-bd1b-8e9911e46293)

**Comment by modmuss50** [comment]
This was fixed.
