### ISSUE TITLE
Mod Template generator gives incorrect mappings when selecting the Split Client and Common Sources option (1.21.4)

### ISSUE THREAD

**Issue by Kfestofil** [FabricMC/fabricmc.net#111]
Basically when you generate a template and use it with the split sources option checked, the mappings you will get are not gonna include some basic minecraft packages (like net.minecraft.client) 

To reproduce just generate 2 templates one with the split sources option and one without, and try to import net.minecraft.client in both of them, you will see that the one with separate sources will not actually be able to find it.

**Comment by Linguardium** [comment]
are you making sure to try to import it in the proper sourceset? This sounds like you are trying to use the main sourceset for client stuff which is the issue footgun that split sources prevents

**Comment by modmuss50** [comment]
Are you trying to import net.minecraft.client within the client sourceset (src/client)? If so its working by design. Split sources disallows you from using client classes in the common (src/main) sourceset.

**Comment by Kfestofil** [comment]
Ok I might've created my datagen providers in the main directory by accident i'm sorry xd
