### ISSUE TITLE
mod template generator forces kebab-case over snake_case for mod ids

### ISSUE THREAD

**Issue by ix0rai** [FabricMC/fabricmc.net#15]
hey!
first off, the mod template generator is amazing, great work with it! I just have one little nitpick that is the generated mod id using `kebab-case` over `snake_case`. At Quilt we encourage `snake_case`, and it would be fantastic if Fabric could adopt this convention too.

**Comment by Technici4n** [comment]
Fabric API uses `kebab-case`, so it will remain encouraged. Adding `snake_case` opt-in seems reasonable though.

**Comment by modmuss50** [comment]
Maybe, I was more thinking of adding an `edit` link to right of the modid, when clicked adds another full input to allow manually specifying the modid?

**Comment by ix0rai** [comment]
I like that idea, maybe with some validation so you can't press generate on something that doesn't follow snake or kebab case
