### ISSUE TITLE
Mod template generator generates a client-only mixin

### ISSUE THREAD

**Issue by Technici4n** [FabricMC/fabricmc.net#16]
![image](https://user-images.githubusercontent.com/13494793/210458569-d6f44d32-5976-4aa6-b9b3-672032486bfa.png)

Is it intended that the mixin is in the `client` block?

**Comment by modmuss50** [comment]
Is this with or without split sources?

**Comment by Technici4n** [comment]
Without

**Comment by Technici4n** [comment]
The mixin itself doesn't depend on any client-side code though.
