### ISSUE TITLE
Light/Dark toggle at bottom for mobile users?

### ISSUE THREAD

**Issue by IMB11** [FabricMC/fabricmc.net#2]
`prefers-media-dark/light` usually doesn't work as intended on most mobile browsers, eg: I am viewing the page when Dark Mode is enabled on my device and browser (chrome):

![Screenshot_20220812-132742_Chrome.jpg](https://user-images.githubusercontent.com/93472213/184353991-0ea843fd-a4a3-41ce-a15d-2e5aeca1409e.jpg)

**Comment by modmuss50** [comment]
I have tested this on chrome using my iPhone and an older andorid device and it works as expected.
