### ISSUE TITLE
Issue with the Package Name field in the Template Mod Generator

### ISSUE THREAD

**Issue by TechPro424** [FabricMC/fabricmc.net#22]
The package name field does not allow names with capital letters such as `a.Bcd` and forcefully converts them into `a.bcd`.

**Comment by modmuss50** [comment]
This is correct behaviour imo, package names should always be lower case.

As per: https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

`Package names are written in all lower case to avoid conflict with the names of classes or interfaces.`
