### ISSUE TITLE
20w14infinite does not match api version

### ISSUE THREAD

**Issue by Danjhop4** [FabricMC/fabricmc.net#5]
On curseforge the 20w14infinite April fools api is a much lower version has the api version shown is for 1.17 and way higher

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
