### ISSUE TITLE
Update wiki for Minecraft 1.20

### ISSUE THREAD

**Issue by mrjasonn** [FabricMC/fabricmc.net#50]
Please update the FabricMC wiki for Minecraft Java 1.20 as soon as possible.

**Comment by modmuss50** [comment]
I reccomend you checkout the blog post we have detailing the 1.20 changes: https://fabricmc.net/2023/05/25/120.html

The wiki is community driven, and will be updated over time, a lot of it should still apply. Feel free to reach on out discord or github discussions if you need any specific help.
