### ISSUE TITLE
(Template Generator Suggestion) Parchment Mappings 

### ISSUE THREAD

**Issue by KhanhPham05** [FabricMC/fabricmc.net#66]
### What ?
- Add a tick box option to use Parchment mappings.

### Why ?
- For the convenience of Parchment-lovers don't have to spend 10 more minutes to lurking around times to times just to add the mappings in their project every time whenever they start a new fabric mod project.

**Comment by Linguardium** [comment]
Are you also suggesting a mojmap tick box so people can generate with mojmap? I feel mojmap is MUCH more common than parchment.

**Comment by KhanhPham05** [comment]
I think I may change from tick box to a selection box so it will fir with many other mappings

**Comment by modmuss50** [comment]
We dont have the parchment versions easily accessible on our website. I think adding a mojmap option will be good enough (see the other open issue)
