### ISSUE TITLE
Template mod generator not including src/main/generated in build.gradle

### ISSUE THREAD

**Issue by O7410** [FabricMC/fabricmc.net#69]
specifically this code:

sourceSets {
&nbsp;&nbsp;&nbsp;&nbsp;main {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;resources {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;srcDirs += [
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'src/main/generated'
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;}
}

a previous version of the generator did put that in build.gradle but now it doesn't
this issue causes the files to **generate** correctly but when running ./gradlew runClient the game just ignores the src/main/generated folder
(src/main/generated is all the assets and data generated by datagen)
(with the data generation option enabled)

**Comment by O7410** [comment]
nice issue number lol

**Comment by Linguardium** [comment]
are you checking the "data generation" box?

**Comment by O7410** [comment]
yeah that's there but it ignores the generated folder
if i add the code with sourceDirs i sent earlier it works

specifically this file scripts/src/lib/template/templates/gradle/groovy/build.gradle.eta
and this commit https://github.com/FabricMC/fabricmc.net/commit/f37ed3ef25269ccaa667f0964b0dbe0099357950
broke it

**Comment by O7410** [comment]
it's a problem in the template mod generator itself, is this the wrong place to report this bug?
