### ISSUE TITLE
Download page is broken in Firefox and Edge

### ISSUE THREAD

**Issue by chimericdream** [FabricMC/fabricmc.net#7]
I suspect something in the recent changes is the culprit here, but nothing jumped out when I was looking at the code. There is a JS error on the page about a re-declaration of a variable (see screenshots below).

Environment:
Windows 11
Firefox and Edge (Chrome seems to work)

![image](https://user-images.githubusercontent.com/198075/188325923-f21a5c76-8918-4d72-997c-27163e268cb8.png)

![image](https://user-images.githubusercontent.com/198075/188325959-a80209be-870d-4a69-9157-2c43f44437e6.png)

Edit:
For reference, this is the entirety of the download page. I have tried multiple browsers and both light/dark themes.

![image](https://user-images.githubusercontent.com/198075/188326106-120ae1d4-0e93-490b-942f-9a8b6946cef3.png)

**Comment by modmuss50** [comment]
Humm, thats very strange, I am unable to reproduce this in Chrome or Safari. Possibly worth trying a hard refresh. (Right click the refresh button with the dev tools open?)

**Comment by chimericdream** [comment]
I've done a hard refresh in both Edge and Firefox with no success. I'm not sure why there would be a random JS error in Firefox and Edge but not Chrome or Safari (especially since Chrome and Edge are functionally identical nowadays). But it's definitely happening.

**Comment by apple502j** [comment]
Could it be due to browser extensions, etc messing it up?

**Comment by chimericdream** [comment]
If it were just Firefox, I'd say maybe. However, I don't use Edge at all except in cases like this where I need to verify a possible bug in a website.

**Comment by modmuss50** [comment]
Unsure if that PR is going to help, will deploy it shortly, and then close once its confimed to fix it.

**Comment by Benonardo** [comment]
I'm unable to reproduce it with firefox 104.0.1 from snap on ubuntu

**Comment by modmuss50** [comment]
Deployed #8 Please try again and let me know if that solves your issues.

**Comment by modmuss50** [comment]
Great, Thanks @JamiesWhiteShirt for figuring that out 👍

**Comment by chimericdream** [comment]
Confirmed working for me as well. Thanks so much!
