### ISSUE TITLE
Downloading the installer can be confusing for new users

### ISSUE THREAD

**Issue by Rafii2198** [FabricMC/fabricmc.net#72]
I am helping over a few communities and I have observed that people are confusing the installer version for fabric with the version that they want to install, and to be fair it can be confusing.
Imagine this, someone never used fabric before and is asked to install version 0.15.0 specifically to play a desired mod, they go to the page and first thing they see is this. What do you think that person would think, that the 0.11.2 refers to the fabric version that will be installed or refer to the version of the program that will install fabric?
![image](https://github.com/FabricMC/fabricmc.net/assets/26695327/232bf642-9601-4723-8782-052d8d77ee2a)

I can tell you that there are people that see just the first option which is fair and try to change that version to 0.15.0 but can't find it there, going back to ask what to do in that situation. After all, this line is even before the download, so it appears like "download xxx fabric version".

I would recommend changing it to be less confusing for these people. Perhaps moving it below the download button next to jar option, saying "Previous versions of the installer" or "Archived versions" or something like that. That way, people that waned to download an older version of the installer could still do that and wouldn't be confusing for anyone. And besides that, why would an average user of fabric even care for the installer version? They just want to install fabric and have fun with mods, and thus I don't see a point in showing it in the main page for download as it draws confusion.

**Comment by Linguardium** [comment]
counterpoint, do people even use old installer versions? it may be worth it to just have an archived version page or something for folks that want to use old installer versions and just serve up the latest from the blue button

**Comment by Rafii2198** [comment]
Is that really a counterpoint, tho? I always believed you use the word counterpoint to like "counter" or go against the idea. But what you said was my idea too.
*(Am I just bad at English?)*

**Comment by modmuss50** [comment]
I think I agree with just removing this version selection. If an advanced user wants to get an older version it's easily findable on maven.

the only time this is used is for beta versions of the installer. For this we could possibly look into doing a staged rollout or add a query parameter to enable the beta by default (if there is one)

**Comment by Rafii2198** [comment]
In case of a beta version, maybe the download button could have a section with that pointing down arrow icon ( ▼ ) on the right that would reveal an alternative download in a dropdown list, in this case for beta version. Maybe if you would have more versions (maybe alpha, or like mirrors or anything like that) then such dropdown could have related items too in the future.
This way, you have a future-proof change. You can even add a page with older versions to that list too.
