### ISSUE TITLE
Fabric API 0.46.6+1.18 requires mcversion 1.18.1

### ISSUE THREAD

**Issue by Linguardium** [FabricMC/fabricmc.net#77]
https://github.com/FabricMC/fabricmc.net/blob/357f2f0b9a37c5e189141e25bf2d604fa7f41c2a/scripts/src/lib/Api.ts#L81

Janky validity check seems to provide wrong fapi version for 1.18

**Comment by modmuss50** [comment]
Fixed, thanks.
