### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by xjsCHINA** [FabricMC/fabricmc.net#97]
The fabric 0.6.0.41 jar is can't download
Please use the PCL2 launcher to download the fabric 0.6.0.41 and you will see the 404 error.

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.

**Comment by xjsCHINA** [comment]
But I'm a Chinese in the China, I can't use the discord on the China. So I only can use GitHub to talk wis you

**Comment by Jamalam360** [comment]
Use the 'discussion thread' link to talk in a GitHub discussion
